### ISSUE TITLE
Model evaluation plots

### ISSUE THREAD

**Issue by JeanDelRosario** [laresbernardo/lares#1]
Hi,

Got to know your code thanks to your excellent article in datascienceplus where you show how to make plots for model evaluation. 
I noticed that in your mplot_splits code that if you choose splits equal to 10 the order of the stacked bar gets fuzzy (you first get 1 then 10 then 2, ...). 
When you are creating the dataframe p, in your code you have:

ggplot(aes(x = as.character(tag), y = p, label = as.character(p),
               fill = as.character(quantile_tag)))

But if we reorder the fill (given by quantile_tag) by quantile we can go past the issue:

ggplot(aes(x = as.character(tag), y = p, label = as.character(p),
               fill = reorder(as.character(quantile_tag),quantile)))

Hope this helps.

**Comment by laresbernardo** [comment]
Super nice observation @JeanDelRosario  
I will implement this improvement right away.
Don't forget to run lares::updateLares() in a few minutes ;)

**Comment by laresbernardo** [comment]
Deploy #435a828
https://github.com/laresbernardo/lares/commit/435a8281d70dc44b6462431086759d71fd82477d
