### ISSUE TITLE
Error in (function (el, elname)  : "axis.text.x.bottom" is not a valid theme element name.

### ISSUE THREAD

**Issue by superzilence** [laresbernardo/lares#12]
If I run the h2o_automl part. I got the following error without any results.
Check results in H2O Flow's nice interface: http://localhost:54321/flow/index.html

Error in (function (el, elname)  : 
  "axis.text.x.bottom" is not a valid theme element name.

I'm using a simple Titanic dataset.
############## 1. Import libraries and data

library(lares)
library(dplyr)
library(ggplot2)

############## 3. Data transformations

df <- balance_data(s, "tag", rate = 1, seed = seed) %>%
  mutate_if(is.numeric, funs(log = log(.+1))) %>%
  select(-name, -ticket, -cabin) %>%
  mutate(tag = as.factor(tag), 
         pclass = as.factor(pclass))

results <- h2o_automl(df, max_time = 60, project = project, seed = seed)

**Comment by superzilence** [comment]
Your new 4.4 version fixed the issues :) and a reload off ggplot2.

**Comment by laresbernardo** [comment]
Glad you figured it out @superzilence 👍
