### ISSUE TITLE
MAPE error ploting in regression model result

### ISSUE THREAD

**Issue by malaaam** [laresbernardo/lares#13]
Hi,
I am Mahabub working as a data scientist in ALSTOM Transport, France.  I have seen your package which is very nice and useful. Thanks for that.

I have an additional query is that , in the regression model result, the errors measures are Adjusted R square, RMSE and MAE. But as per the requirement of my project I also want to calculate and show MAPE in this plot.
So, could you please advice how can I include MAPE on the same graph?

**Comment by laresbernardo** [comment]
Hey @malaaam Glad you are using my library!
Please, can you tell me why do you want MAPE specifically, additionally or instead the other metrics shown in the plot? I'm curious...
On the other hand, if you need to get the metric (MAPE), you can access it with `lares::mape(real_values, predicted_values)` or with the pre-calculated `results$metrics$error` data frame that returns the `lares::h2o_automl` function (I guess it's what you are using).
Additionally, if you wish to plot the results with that metric shown, you can check the [mplot_lineal function](https://github.com/laresbernardo/lares/blob/master/R/model_plots.R#L660) and simply copy/paste it as a new local function, changing the metrics you wish to plot in the inner `labels` object.
On my side, I guess I could let the user select which metrics are shown in the plot by adding a new parameter to the function... something like `metrics=c("RMSE","MAPE","R2")`
Hope that works out for you ;)
