### ISSUE TITLE
lares - plot_timeline sorts alphabetically

### ISSUE THREAD

**Issue by anelda** [laresbernardo/lares#14]
Hi @laresbernardo! Thanks so much for developing this fun and easy to use package.

I tried to use it on my own data (deliverables for a project), but find that the deliverables (in your case the events) are sorted according to the alphabetical order of the groups.

I can share my script and data with you if you want to explore?

Thanks! Anelda

**Comment by anelda** [comment]
@laresbernardo I think this happens when you create [`cv_long`](https://github.com/laresbernardo/lares/blob/master/R/other_plots.R) `line 42`.

If you rather use `type = rep(factor(df$Type, order = TRUE),2)` this might prevent the automatic reordering.

**Comment by laresbernardo** [comment]
Hey @anelda glad you are enjoying the library. I use it every day for almost everything!
I'll push that change for you! Thanks for sharing your case and solution. That was easy 👍

**Comment by laresbernardo** [comment]
Done: https://github.com/laresbernardo/lares/commit/ddd2cf7808bd09b8474f056726c5241b1f6db571
