### ISSUE TITLE
object 'cats' not found

### ISSUE THREAD

**Issue by theiman112860** [laresbernardo/lares#18]
Hi,

Great package! Thank you!! After I run the H20 autoML I get the following error:

Check results in H2O Flow's nice interface: http://localhost:54321/flow/index.html
Model selected: GBM_1_AutoML_20191030_214222
NOTE: The following variables were NOT important: "VEHICLE_LICENSE_STATE_OTHER", "REPORT_STATE_OTHER", "ACCESS_CONTROL_DESC_Full.Control", "ACCESS_CONTROL_DESC_No.Control"
>>> Running predictions for data2$tag...
Error in grepl(" ", cats) : object 'cats' not found

[ART.txt](https://github.com/laresbernardo/lares/files/3791814/ART.txt)

Any ideas on what object "cats" is or how I can get it to work? Thank you!!

Sincerely,

tom

**Comment by theiman112860** [comment]
Below is a subset of the data

[sept_crash_data.zip](https://github.com/laresbernardo/lares/files/3793389/sept_crash_data.zip)

**Comment by laresbernardo** [comment]
Hi @theiman112860 
Thanks for getting in touch and reporting your issue. I've added a small peace of code that should fix this error. Please, run `updateLares()` to update the library, close RStudio, open it, and try again! Let me know how it goes.
BTW: No need to run `h2o.init()` before you call the function ;)

**Comment by theiman112860** [comment]
Hi laresbernardo,

Now I am getting another error:

"In error/tag :
  longer object length is not a multiple of shorter object length"

Weird isn't it? Any ideas on what is going on? Thank you again!

Sincerely,

tom

**Comment by laresbernardo** [comment]
Let's check what's wrong here. Try renaming your data3 tag column to something like "tag" (`data3<-data.frame(data2[,feat_imp_df], tag = data2$tag)`)

Please, run these 3 examples to see if it's the library or something with your data. These 3 cases should work!
```
library(lares)
library(dplyr)

data(dft)
dft <- dft %>% select(-Ticket, -PassengerId, -Cabin)

# Classification: 2 class
r <- h2o_automl(dft, y = "Survived", max_models = 1, target = "TRUE")
# Classification: 3 classes
r <- dft %>% select(-Fare) %>% h2o_automl(y = "Pclass", impute = TRUE, max_models = 1)
# Regression
r <- dft %>% h2o_automl(y = "Fare", ignore = c("Pclass","Cabin"), max_models = 1)
```

**Comment by theiman112860** [comment]
Hi Laresbernardo,

Thank you for the quick response!!!!!  All of your examples worked. I renamed tag like you said i.e. data3<-data.frame(data2[,feat_imp_df], tag = data2$tag)) .. It worked i.e. no errors. However, it did not generate any results.. It also mentioned generating plots.. I cant find those either.. Any ideas?  Thank you again!! Sorry to be a pain in the neck..

Sincerely,

tom

**Comment by theiman112860** [comment]
The output is:
Check results in H2O Flow's nice interface: http://localhost:54321/flow/index.html
Model selected: GBM_1_AutoML_20191031_075159
NOTE: The following variables were NOT important: "VEHICLE_LICENSE_STATE_OTHER", "REPORT_STATE_OTHER", "ACCESS_CONTROL_DESC_Full.Control", "ACCESS_CONTROL_DESC_No.Control"
>>> Running predictions for tag...
>>> Generating plots...
Process duration: 55.77s
       rmse        mae      mape        mse     rsq    rsqa
1 0.1907409 0.05760291 0.9113939 0.03638208 0.01379 0.01375
Error in beep() : could not find function "beep"
> results
Error: object 'results' not found

**Comment by theiman112860** [comment]
I installed beepr and that fixed it!!!!!

**Comment by laresbernardo** [comment]
Great! That shouldn't happen. If you don't have `beepr` library installed, the function should skip the alarm. You could set the `alarm` parameter to `FALSE` or if it's `TRUE` and you don't have it installed, nothing should happen. I'll check why that didn't happen to you.

**Comment by theiman112860** [comment]
The graphics are really nice!! Thank you again!!

**Comment by laresbernardo** [comment]
Thanks! Hope they are useful as well! xD

**Comment by theiman112860** [comment]
Hi Bernardo,
They are very useful!! Thank you!!
Sincerely,
tom

-----Original Message-----
