### ISSUE TITLE
Non-zero Exit

### ISSUE THREAD

**Issue by nomankhalid** [laresbernardo/lares#20]
I am trying to install lares package. Windows 10 64 bit, RStudio version 1.1.419, R version 3.6.1
I am installing like this:
install.packages('devtools')
devtools::install_github("laresbernardo/lares")

I am getting the following error when installing:
Error: Failed to install 'lares' from GitHub:
  (converted from warning) installation of package ‘C:/Users/admin/AppData/Local/Temp/RtmpYXIxIf/file2ca01cf1145d/lares_4.7.tar.gz’ had non-zero exit status

Please help

**Comment by laresbernardo** [comment]
Hi @nomankhalid Glad you are trying to install ´lares´
I know Github had some issues these last days with external connections. Maybe it was a temporal problem.
Could you please share with me your `sessionInfo`?
Is this the first time you install the library or is it an update?
Please, open a fresh R session and install it as you've tried and share with me what happens, step by step.

**Comment by nomankhalid** [comment]
Hi. Here is my session info:

sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1    yaml_2.2.0    

This is the first time I am installing this library and I tried opening a fresh R session and installing just this library, but it returned the same error. 
![image](https://user-images.githubusercontent.com/7050989/78540945-4faf8680-780e-11ea-8d5a-cecaab801ef1.png)

**Comment by laresbernardo** [comment]
Hi! This must be a Windows / `.libPaths` issue. I do not have a Windows laptop to replicate this problem you are having but I guess that setting the `R_LIBS_USER` parameter in your `. Renviron` might do the trick.
You might find this thread useful: https://community.rstudio.com/t/help-regarding-package-installation-renviron-rprofile-r-libs-r-libs-site-and-r-libs-user-oh-my/13888/8

**Comment by laresbernardo** [comment]
Due to no further reply, closing this issue. Feel free to reopen if you find an error regarding the library.
