### ISSUE TITLE
corr_cross function, contains argument, inescapable "Faceting variables" error?

### ISSUE THREAD

**Issue by RickPack** [laresbernardo/lares#22]
It looks to me like the contains argument of the corr_cross function always returns a "Faceting variables" error. 

Can someone confirm it still works?

I am using R 4.0.0 and all CRAN packages have been updated. Lares package version is 4.8.4.

```
lares::corr_cross(mtcars,
           contains = "mpg")
```

**Error: Faceting variables must have at least one value**

**Comment by laresbernardo** [comment]
Hi @RickPack 

Thanks for reaching out. I think that this is what you actually are looking for: `corr_var(mtcars, mpg)`
<img width="694" alt="Screen Shot 2020-06-29 at 17 41 18" src="https://user-images.githubusercontent.com/25909073/86053999-c041fa00-ba2f-11ea-9f26-ae1f26702d73.png">

On the other hand, when using `corr_cross`, the `contains` parameter actually had a bug. Works when intended to be used on categorical values, as shown in the example of the [clusterKmeans](https://laresbernardo.github.io/lares/reference/clusterKmeans.html) function but the `redundant` argument had a bad logic around it. Fixed now!
