### ISSUE TITLE
Error while trying out example code

### ISSUE THREAD

**Issue by ElKron** [laresbernardo/lares#23]
Dear Bernardo,

I would very much like to use this package to supplement my own analysis of my investments. I tried to recreate the plots on [your datascience+ post](https://datascienceplus.com/visualize-your-portfolios-performance-and-generate-a-nice-report-with-r/).

Unfortunately, I encountered the following error while running the code with the dummy portfolio provided:
```
> file <- system.file("docs", "dummyPortfolio.xlsx", package = "lares")
> df <- stocks_file(filename = file)
> dfp <- stocks_obj(df)
>>> Downloading historical data for each stock...
 00:00:04 [==============================================================] 100% | DONE                                                             
Calculations ready...
Error: Can't subset elements that don't exist.
x Location 1 doesn't exist.
i There are only 0 elements.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In theme_lares2(legend = "top") :
  Font Arial Narrow is not installed, has other name, or can't be found
```
Do you have an idea of the source this error? Additionally, with a first try on part of my own portfolio, I get an error message related to dividends:
```
> dfp <- stocks_obj(df2)
>>> Downloading historical data for each stock...
Error: Problem with `mutate()` input `Dividend`.
x Column `DivReal` not found in `.data`
i Input `Dividend` is `.data$DivReal * .data$CumQuant`.
i The error occurred in group 1: Symbol = "MJP.PA".
Run `rlang::last_error()` to see where the error occurred.
```
The dividend problem is maybe related to my portfolio containing accumulating index funds?

In any case thank you for your help!

ElKron

**Comment by laresbernardo** [comment]
Hi @ElKron 
I was messing with the number formats on the plots and broke something.. I've just fixed it! Please, update the library, retry with the dummy example, and let me know if it worked.
Re your own portfolio, I "think" I know what could be but as I can't replicate your particular case, I'm not 100% sure I've fixed it. Please, also try it again with the updated version, and let me know. If you have a reproducible example you could share, much better. Maybe the same portfolio but with 1 stock per ticker?
You can update the library with: `lares::updateLares()`
Cheers!

**Comment by ElKron** [comment]
Thank you for this very quick reply. At this point, both issues seem fixed. I still need add my full portfolio. If any new issues should arise, I will let you know.

Thank you again!
