### ISSUE TITLE
Portfolio performance: some suggestions for functionality

### ISSUE THREAD

**Issue by ElKron** [laresbernardo/lares#25]
Hi Bernardo,

Some suggestions for the portfolio performance functionality. Of course, you decide which you deem useful!

- Have an option to show everything in another currency (e.g. euro, GBP...) for the plots and the reporting. In principle this is just a quality of life improvement if all investments are in the same currency anyway.
- Add functions to calculate and plot the _internal rate of return_ (IRR) of the full portfolio (investments + cash). The internal rate of return is the interest rate that you apply to all your deposits (annually compounded) at the time of deposit and which yields the most recent full portfolio value. For a long term diversified portfolio, this is often estimated around 6-8% so it is a nice performance measure for your investment strategy. I prefer to include (unused) cash from deposits in my portfolio value since it is an integral part of ones investment strategy: when to leave more cash for investments and when not. [More information on IRR](https://en.wikipedia.org/wiki/Internal_rate_of_return). IRR can be calculated through an optimization approach for root-finding. The plotting functionality would probably be very similar to what you already do for the ROI. Below is an example from my own calculations (IRR from start of investments up to day t, including the mean IRR over all calculations; you could also go for a _daily change in IRR_-graph).
![afbeelding](https://user-images.githubusercontent.com/69209613/89560736-ca69cc00-d817-11ea-935a-391bf5f9bb85.png)
- Optionality for foreign currencies: would require scraping FX data and incorporating that so not a quick fix according to my experience.

Thank you for your consideration!

ElKron

**Comment by laresbernardo** [comment]
Thanks for your feedback and suggestions @ElKron  
- The first point was (kind of) answered [in this thread](https://github.com/laresbernardo/lares/issues/24#issuecomment-670539044) when I mentioned the currencies.
- The second one, I guess the same answer applies (no time / haven't needed it). But, I guess that as a short-term not-ideal solution, you could add those returns as cash deposited into your account. You won't be able to visualize the returns with the library yet but you'll keep a correct balance. Or, if it's a fixed rate (more often not), an additional argument could be passed to the `stocks_obj()` to calculate/plot these returns as well. Can't promise anything soon ;)

**Comment by ElKron** [comment]
Thank you for your consideration. I understand your answer to point 1 and 3. If you wouldn't use it, you shouldn't spend time on it. At the moment, it is also not the biggest concern for me due to having closed/sold all my non-euro positions.

I'm not sure if I explained my second point clearly enough. The _internal rate of return_ is not an actual return/dividend on top of the portfolio transactions. It is a theoretical concept to calculate the performance of the portfolio. It is related to your ROI calculations but instead of doint this calculation for the portfolio value day-by-day (i.e. calculated between time t -> t+1, t+1->t+2,...), it is calculated from a fixed starting point (start of investments), relative tot he cumulative amount of deposits.

If I'm able to accurately reflect my current portfolio value with your tool, I will take a look to see if it is easy to incorporate myself and send a proposal to incorporate in the tool.

**Comment by laresbernardo** [comment]
Closing for now...
