### ISSUE TITLE
Suggestion for functionality

### ISSUE THREAD

**Issue by mileta1976** [laresbernardo/lares#26]
Hello Bernado, your package certainly has great potential !

Could you add this functionality:
https://towardsdatascience.com/my-secret-sauce-to-be-in-top-2-of-a-kaggle-competition-57cff0677d3c

Thank you !

**Comment by NikitaEGroot** [comment]
Hi, thanks for your amazing work! I might be missing something obvious, but is there any way to add titles and remove the "Ranked Cross-Correlations" heading from the corr_cross?

**Comment by laresbernardo** [comment]
Hi @NikitaEGroot thanks!
Yes, you can actually do something like:
```
... + ggplot2::ggtitle("This is my new title")
```

**Comment by NikitaEGroot** [comment]
> Hi @NikitaEGroot thanks! Yes, you can actually do something like:
> 
> ```
> ... + ggplot2::ggtitle("This is my new title")
> ```

Thank you so much! I didn't realize the whole plot worked with ggplot2, this is perfect!
