### ISSUE TITLE
Not an Issue - A Question

### ISSUE THREAD

**Issue by ZellW** [laresbernardo/lares#3]
Great work.  Can you hear my applause?

A quick request:  Would you provide a bit more explanation of the Tag vs Score Splits Comparison?  I am not able to really understand how to interpret it.

Similarly, I am not sure I understand the business value of Cuts by Score.

I appreciate any detail you might provide.  Hopefully others will find this helpful too.

Much thanks for sharing your work.

**Comment by laresbernardo** [comment]
Hey @ZellW 
Thanks for your "applause" 👍 
I have written about those two in this post: [Machine Learning Results in R: one plot to rule them all! (Part 1 – Classification Models)](https://datascienceplus.com/machine-learning-results-one-plot-to-rule-them-all/)
You can also run `devtools::install_github("laresbernardo/lares")` and `?lares::mplot_splits` / `?lares::mplot_cuts`
Basically:
1. mplot_splits: let's you do a Pareto kind of split on your data, based on your scores.
2. mplot_cuts: let's you know where to cut and put your max/min threshold for your score if needed.
