### ISSUE TITLE
Correlations expressed as percentages

### ISSUE THREAD

**Issue by teecrow** [laresbernardo/lares#31]
Hi there, very nice package here - as a social scientist I have found the correlation functions particularly useful (and beautiful) for exploring correlations.

I might suggest a small tweak -- in the corr_cross function and a few others, correlations are expressed as percentages, but this is really never done in the sciences that heavily use correlations. Perhaps there could be an argument added to these functions which would keep it in the original _r_ metric (-1 to 1, or abs(corr)? 

Expressing it as a percentage can lead to confusion for a couple main reasons:  

1. A correlation coefficient ranges from -1 to 1 -- and a percentage can not be negative. (Of course this only applies to the functions that do not take the absolute value of the correlation.)
2. Expressing it as a percentage may lead people to confuse it with the coefficient of determination, or _R_^2, which is sometimes expressed (and thought of) as a percentage, because it is the percentage of the variance in the outcome variable explained by the predictor(s). 
3. Most scientists examining correlations will want them in the -1 to 1 metric (or the absolute value of that).
4. I noticed all this upon finding a bug when examining some data (see below): **There appears to be a bug when setting the argument `type = 2` in the corr_cross function**: for correlations ranging from .51 to .59, the x-axis is mislabelled. Because I don't desire percentages anyway, this is easily sidestepped by deleting all arguments to the final call to `scale_y_continuous` within the function. Or even better, setting the arguments to `limits = c(min(ret$corr), max(ret$corr))` to scale the axis nicely to the data.

![image](https://user-images.githubusercontent.com/51515693/113520000-077c8e80-955e-11eb-98e4-effe9ae668a2.png)

And with the arguments removed in `scale_y_continuous`:
![image](https://user-images.githubusercontent.com/51515693/113520009-195e3180-955e-11eb-9b64-b5af8b89cdc4.png)

In the next ~3-6months, once I learn to use git, I am happy to make a pull request and add this on behalf of anyone else who may have a similar suggestion!

Hopefully this is helpful, and it's really minor -- thanks again for the useful package!

**Comment by laresbernardo** [comment]
Hi @teecrow 
Thanks for your detailed feedback! Glad you are using the library for your analyses :) 
I do agree with you that the "correct" way to show correlations is NOT with percentages, but they do help with visualizations (less zeroes at least). I will consider your feedback and make some changes to enable both POVs or do something about it.
Regarding the `scale_y_continuous` usage, I agree it's not formatting as it should for small numbers (that's a ggplot2 thing I can surely fix for ur plots). 
I would appreciate if you could share a reproducible example so I can replicate your plots with fixed/changed results.

**Comment by laresbernardo** [comment]
Check out new plots format here: https://laresbernardo.github.io/lares/reference/corr_cross.html

**Comment by teecrow** [comment]
> Check out new plots format here: https://laresbernardo.github.io/lares/reference/corr_cross.html

Looks great -- easier to interpret, and the problem with the small numbers is gone!
