### ISSUE TITLE
Error en corr_var

### ISSUE THREAD

**Issue by BaltiBoix** [laresbernardo/lares#32]
![image](https://user-images.githubusercontent.com/13628812/115851584-6760a980-a427-11eb-9769-4a554f5bcc5d.png)

**Comment by laresbernardo** [comment]
Hi @BaltiBoix 
I guess this is not an error on the code but what's happening is that there is no correlation with less than 0.05 as pvalue. I will pass a friendlier "error" message when this happens so the user understands what happened.
Reproducible example:
```
library(lares)
library(tidyverse)
A <- tibble(x=1:4,y=c(0,1,2,7),z=c(5,9,7,3))
corr_var(A, x)
corr_var(A, x, max_pvalue = 0.05)
```

**Comment by laresbernardo** [comment]
Ok, now you'll get:
```
> corr_var(A, x, max_pvalue = 0.05)
[1] variables corr      pvalue   
<0 rows> (or 0-length row.names)
Warning message:
In corr_var(A, x, max_pvalue = 0.05) :
  There are not enough observations to plot. Check your 'max_pvalue' input
  ```

**Comment by BaltiBoix** [comment]
Using max_pvalue=0.99 gives the same error.

Thanks

Balti

**Comment by laresbernardo** [comment]
That's correct, because the pvalue for each variable is 1:
```
> corr_var(A, x, plot = FALSE)
  variables    corr pvalue
2         y  0.9135      1
3         z -0.4000      1
```

**Comment by BaltiBoix** [comment]
Sorry, I think that I have misinterpreted the pvalue. I thought it was
referred to the null hypothesis of corr=0.

Thank you, your package is very useful!

Balti
