### ISSUE TITLE
different p-values for correlations

### ISSUE THREAD

**Issue by michellekee** [laresbernardo/lares#34]
Hi,
I'm new and happened to chance upon your package. :) 

I love the corr_var function, but realised that it gives me different p-values.

```{r}
A <- tibble(x=1:4,y=c(0,1,2,7),z=c(5,9,7,3))
corr_var(A,x, plot =F, type = "spearman")
```

  variables    corr pvalue
2         y  0.9135      1
3         z -0.4000      1

```{r}
cor.test(A$x, A$z, method = "spearman", exact = F)
```

Spearman's rank correlation rho

data:  A$x and A$z
S = 14, p-value = 0.6
alternative hypothesis: true rho is not equal to 0
sample estimates:
 rho 
-0.4 

Could you please kindly advise? Thank you so much!

**Comment by laresbernardo** [comment]
Hi @michellekee The code was passing a matrix with 1s when `pvalues` parameter was not set. I've explicitly added the `pvalues` parameter to `corr_var` now, which is TRUE by default, ignored when `plot = TRUE`. Thanks for reporting this and let me know if that works out for you.
**Note**: you can now also pass the `exact` parameter from `cor.test` to `corr_var()` in case you'd need to.

**Comment by michellekee** [comment]
Thank you very much! This works perfectly! :)
