### ISSUE TITLE
link to "dummyPortfolio.xlsx" is dead

### ISSUE THREAD

**Issue by L30P30** [laresbernardo/lares#36]
Hi, I'm keen to try this but the link to the dummy portfolio 404s

**Comment by laresbernardo** [comment]
Hello @L30P30 thanks for reporting this.
Would you mind telling me where are you trying to get the file from? We have it hosted here and it's working OK: `/inst/docs/dummyPortfolio.xlsx`.
You can download it directly using this [link](https://github.com/laresbernardo/lares/blob/main/inst/docs/dummyPortfolio.xlsx?raw=true) as well.
