### ISSUE TITLE
corr_cross plot incomplete

### ISSUE THREAD

**Issue by deschan5** [laresbernardo/lares#39]
Hi, thank you for your package, really easy to use and clear data within minutes! However, I might have found an issues regarding the corr_cross plot. Using plot=T without ceiling or max_pvalue, I found there are pairs of variables not displayed in the corr_cross plot. 
I double-checked with other packages as well as with corr_cross(df, plot=F, pvalue=T) or corr_var for the individuals pairs, which verified the underlying correlations to be there, but not plotted.
Now, when I created dummies (to upload a reproducible sample here), then the correlations are plotted correctly! I have no clue what to do next....
Thank you and have a nice day

**Comment by laresbernardo** [comment]
Hi, @deschan5 
Thanks for reporting this. I guess you could share a reproducible example so I can dig deeper into this case for you and get a fix ASAP. You can anonymize and post your data here if you'd like or send it to my user @ gmail.com so I can personally check that out. 
Did you check if those combinations not shown are correlations of X to Y / Y to X?
Have a nice well too :)

**Comment by deschan5** [comment]
Hi,
sorry for the late response...
The issue might have something to do with column names: as I wanted to create a anonymized sample set, it worked perfectly (replacing my variable names with numbers).
Hope that helps.
Cheers

**Comment by laresbernardo** [comment]
Hey @deschan5 were you able to check if the issue you had was actually fixed before renaming your columns? I'm a bit concerned this might be affecting other users and the bug's still there

**Comment by deschan5** [comment]
Hey, I already did this steps back in February shortly after I opened this topic. I simply wasn't able to explain it in a timely manner. Hope this help. Anyway, users should always doublecheck what they are doing, right :) don't worry

Cheers

 
 

Gesendet: Montag, 28. März 2022 um 14:47 Uhr
Von: "laresbernardo" ***@***.***>
An: "laresbernardo/lares" ***@***.***>
Cc: "deschan5" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [laresbernardo/lares] corr_cross plot incomplete (Issue #39)


 

Hey @deschan5 were you able to check if the issue you had was actually fixed before renaming your columns? I'm a bit concerned this might be affecting other users and the bug's still there
