### ISSUE TITLE
Quantile split plot legend is wrong for discrete tags

### ISSUE THREAD

**Issue by iasonkon** [laresbernardo/lares#4]
https://github.com/laresbernardo/lares/blob/8cb4b3af25e03747a444cd055a3267bae2405365/R/model_plots.R#L531

This probably needs to be divided by 100 after rounding to show correct values in legend

**Comment by laresbernardo** [comment]
Thanks for detecting this issue @iasonkon 
Fixed it in a more elegant way, using the `signif` function, so it will look nice for 0-1 and 0-100 scores! ;)
