### ISSUE TITLE
Is it possible to auto-compare different models?

### ISSUE THREAD

**Issue by CWen001** [laresbernardo/lares#40]
Hello, and thanks for this nice package. After using `pycaret` in python, I found `lares` quite convenient to finish the low-code auto-ML jobs.

A question about the functionality, Please. Is it possible for `lares` to compare different models? This is one killer feature of `pycaret` with the help of `compare_models()`, which gives the user a summary table. For simple academic use, it also helps demonstrate how different models perform as a fast exploration.

**Comment by laresbernardo** [comment]
Hi @CWen001 thanks for your nice feedback. 

Given your comparing model request, I have in mind two possible ways to do so:

1. When running `h2o_automl()` you'll get a leaderboard will all the generated models and a dataframe that compares the main metric chosen to pick the winner

2. We have `model_metrics()` function that will give you a bunch of metrics you can use to compare any model. You'd have to run that for each model you'd like to compare and gather them up in a summary table. Feel free to develop this as a function and we could implement it in `lares`.

Cheers!

**Comment by laresbernardo** [comment]
Closing for now...
