### ISSUE TITLE
geom_text_repel() as substitution for geom_text()

### ISSUE THREAD

**Issue by bookerbn1** [laresbernardo/lares#42]
Have you considered using `ggrepel::geom_text_repel()` for the labeling the highest correlations in the local plot instead of `geom_text()` to prevent overlapping labels?

![image](https://user-images.githubusercontent.com/76966996/207933828-86ee7c01-a18d-413e-8fec-f12f4881ce2e.png)

**Comment by laresbernardo** [comment]
Hi @bookerbn1 thanks for the feedback. Yes, I've actually considered it but I tend to avoid [adding more dependencies](https://github.com/laresbernardo/lares/blob/main/DESCRIPTION) to the package. You could modify it manually though by playing with the `ggplot` object the function returns.

**Comment by laresbernardo** [comment]
Thanks for your comment and for sharing your solution @bookerbn1! Pretty useful for follow-ups. Cheers!
