### ISSUE TITLE
Error in `dplyr::filter()`:

### ISSUE THREAD

**Issue by ms1948** [laresbernardo/lares#43]
When I run the command: 
r <- h2o_automl(df, y = BG, max_models = 1, impute = FALSE, target = "C3")
the SELECTED MODEL: XGBoost_1_AutoML_4_20230324_103413 produces the following error msg:
Error in `dplyr::filter()`:
ℹ In argument: `.data$importance < 1/(nrow(imp) * 4)`.
Caused by error in `.data$importance`:
! Column `importance` not found in `.data`.

**Comment by laresbernardo** [comment]
Hi @ms1948 I can't seem to be able to replicate your issue with the `dft` dataset and a dummy example. Can you please share a reproducible example?

**Comment by ms1948** [comment]
library(lares)
library(gdata)
rm(list=ls())
a=read.xls("file.xls")
names(a)
b=data.frame(a[2:27])
r=lares::h2o_automl(b, y = CAT_C3, 
                  max_models = 1, 
                  impute = FALSE, 
                  target = "CAT", 
                  scale = TRUE,
                  start_clean=TRUE,
                  alarm = TRUE)

[file.xls](https://github.com/laresbernardo/lares/files/11066535/file.xls)

**Comment by laresbernardo** [comment]
Thanks, I was able to replicate this issue.  I'm getting the following error because h2o doesn't provide an varimp result for this model.
```
h2o.varimp(m)
Warning message:
This model doesn't have variable importances 
```
Will add a logic to not crash but simply skip this result when this happens.

**Comment by ms1948** [comment]
Ok. Thanks.

**Comment by laresbernardo** [comment]
I've just updated the dev version. Please, update with `lares::updateLares()`, restart your R session, and retry. Close this ticket once you validate it's running correctly on your end.

**Comment by ms1948** [comment]
Ok, it works. Thanks.
