### ISSUE TITLE
Getting error in corr_varr

### ISSUE THREAD

**Issue by solsterg98** [laresbernardo/lares#46]
Hi Lares,

I am currently trying to use your 'corr_varr' package and I am getting the following error:

"Not a valid input: _Feature_ was transformed or does not exist.".

The variable is numeric and the dataset itself is completely numeric so not sure what the problem is.

Any help would be greatly appreciated :)

**Comment by solsterg98** [comment]
Figured it out! I had put my feature as 'dataset$feature' when it only needed to be the feature.

**Comment by laresbernardo** [comment]
Great, good catch! I'll consider adding the user passing a vector instead of tidy-friendly variables as well as an option. Glad you sorted this out for yourself.
