### ISSUE TITLE
error due to h2o package

### ISSUE THREAD

**Issue by AntoineSoetewey** [laresbernardo/lares#48]
Hello,

I'm trying to use the `corr_cross()` function from the `{lares}` package, but I encounter an issue, I suppose due to the `{h2o}` package:

![Screenshot 2023-09-05 at 09 39 06](https://github.com/laresbernardo/lares/assets/17910063/14fec335-f3fd-44fa-b1f6-4db77d2414b4)

I tried to install the h2o package (`install.packages("h2o")`) without any success.

Anyone had this issue in the past and managed to fix it?

Any help would be greatly appreciated!
Antoine

**Comment by laresbernardo** [comment]
Hi @AntoineSoetewey thanks for reporting your issue. Please try the following:
- Set `options(timeout=500)`
- Manually install `h2o` using CRAN version or GitHub version
- Re-install `lares` (CRAN or GitHub version as well)
After they have been successfully installed, you should be good to go. Also, try resetting your R session while doing these steps to avoid a clash of versions.
