### ISSUE TITLE
Problem installing the package

### ISSUE THREAD

**Issue by nikosGeography** [laresbernardo/lares#49]
I am trying to install the package but the `h2o` package cannot be installed. What I have tried is:

1. `install.packages("lares")` gives: ```
Warning in install.packages :  downloaded length 0 != reported length 0
Warning in install.packages :  URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) :   download from 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip' failed
Warning in install.packages :  download of package ‘h2o’ failed
```

2. Then I tried to do `install.packages("h2o")` but I get this error: ```
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip'. Content type 'application/zip' length 250589495 bytes (239.0 MB)
downloaded 167.3 MB
Warning in install.packages :  downloaded length 0 != reported length 0
Warning in install.packages :  URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip' failed
Warning in install.packages :  download of package ‘h2o’ failed
```

3. Then I tried `install.packages("h2o", dependencies = TRUE)`. The errors: ```
Warning in install.packages :
  downloaded length 0 != reported length 0
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/windows/contrib/4.3/h2o_3.42.0.2.zip' failed
Warning in install.packages :  download of package ‘h2o’ failed
```
4. Then I tried to follow the instructions from [here](https://h2o-release.s3.amazonaws.com/h2o/rel-lambert/5/docs-website/Ruser/Rinstall.html). The same error.

Any ideas why I am getting this error? I can't use `lares `without the `h2o`. I am using `R` 4.3.1, `RStudio` 2023.09.0 Build 463, Windows 11.

**Comment by laresbernardo** [comment]
Please try this: #48

**Comment by nikosGeography** [comment]
It worked. And the solution:
```
options(timeout = 500)
install.packages("h2o")
install.packages("lares")
```
