### ISSUE TITLE
holidays(countries = "Italy", years = 2022) issue

### ISSUE THREAD

**Issue by F041** [laresbernardo/lares#50]
Output:

# A tibble: 9 x 10
  holiday    holiday_name                  holiday_type     national observance bank  nonwork season hother county
  <date>     <chr>                         <chr>            <lgl>    <lgl>      <lgl> <lgl>   <lgl>  <lgl>  <fct> 
1 2022-03-02 Ash Wednesday                 Observance       FALSE    TRUE       FALSE FALSE   FALSE  FALSE  Italy 
2 2022-03-19 Father's Day                  Observance       FALSE    TRUE       FALSE FALSE   FALSE  FALSE  Italy 
3 2022-03-20 March Equinox                 Season           FALSE    FALSE      FALSE FALSE   TRUE   FALSE  Italy 
4 2022-04-15 Good Friday                   Observance       FALSE    TRUE       FALSE FALSE   FALSE  FALSE  Italy 
5 2022-04-17 Easter Sunday                 National holiday TRUE     FALSE      FALSE FALSE   FALSE  FALSE  Italy 
6 2022-04-18 Easter Monday                 National holiday TRUE     FALSE      FALSE FALSE   FALSE  FALSE  Italy 
7 2022-04-25 Liberation Day                National holiday TRUE     FALSE      FALSE FALSE   FALSE  FALSE  Italy 
8 2022-04-25 The Feast of St Mark (Venice) Local holiday    FALSE    FALSE      FALSE FALSE   FALSE  TRUE   Italy 
9 2022-11-01 All Saints' Day               National holiday TRUE     FALSE      FALSE FALSE   FALSE  FALSE  Italy 

It doesn't give many other days like Christmas
compelte list: https://travel.thewom.it/destinazioni/news-lowcost/ponti-2023.html

It would help also to have a column for "bridge days" (ponti)

**Comment by laresbernardo** [comment]
Running exactly the same code as in the title I'm getting `A tibble: 26 × 10` with all Italy holidays for 2022, including Christmas. Same for 2023. As for bridge days, maybe add a conditional new column checking for Fridays and Mondays I guess.
