### ISSUE TITLE
Terminology: Independent or dependent variable?

### ISSUE THREAD

**Issue by shleeneu** [laresbernardo/lares#51]
In the lares package, I noticed what you mean by "independent" variable is the *outcome* variable. However, in most textbooks, the outcome variable is commonly referred to as the "response" or "dependent" variable, whereas the "independent" variable mostly refers to "predictors" or "features".  See the textbook ["An Introduction to Statistical Learning with Applications in R"](https://drive.google.com/file/d/106d-rN7cXpyAkgrUqjcPONNCyO-rX7MQ/view), page 16.

I'd suggest updating the terminology wherever it appears.

**Comment by laresbernardo** [comment]
Thanks for your feedback @shleeneu 
Can you share a couple of examples of where this is happening in the code/documentation? We can fix whatever is wrong and consider improving the wording for parameters if needed.

**Comment by laresbernardo** [comment]
Ah yes, you're absolutely right @shleeneu Don't know why it took so long for someone (including me) to notice. Will fix it ASAP! Thanks for reporting it

**Comment by laresbernardo** [comment]
I've fixed the documentation. There was no need to change any parameter name so it was an easy fix. Feel free to close this issue if you agree

**Comment by laresbernardo** [comment]
Fixed, thanks!!
