### ISSUE TITLE
font_exist is false if ttf file in subdir

### ISSUE THREAD

**Issue by louisjanin** [laresbernardo/lares#53]
Hi Bernardo,

I use Robyn for my company and tried to fix the warning "Arial Narrow not installed". I came accross the font_exists function from the lares package and I think my problem was that the font was installed but inside a nested directory.
So what I did was copy it in /usr/share/fonts which fixed the problem for me:
```
rproc-00:/usr/share/fonts# ls
'Arial Narrow.ttf'   cmap   cMap   fonts-go   opentype   truetype   type1   woff   X11
rproc-00:/usr/share/fonts# ls truetype/msttcorefonts/Arial*
 truetype/msttcorefonts/Arial_Black.ttf         truetype/msttcorefonts/Arial_Italic.ttf
 truetype/msttcorefonts/Arial_Bold_Italic.ttf  'truetype/msttcorefonts/Arial Narrow Regular.ttf'
 truetype/msttcorefonts/Arial_Bold.ttf          truetype/msttcorefonts/Arial.ttf
```
So i just wanted to let you know, because maybe the function could look in subdirs..
Thanks and sorry for the not so well formatted issue...

**Comment by laresbernardo** [comment]
Hi @louisjanin thanks for reoirting this issue and for sharing you're also using Robyn :)

What OS are you at? Can you share your `R.version$os`? (Probably linux-gnu) 

Also, notice `/usr/share/fonts/` is [also included](https://github.com/laresbernardo/lares/blob/main/R/other_functions.R#L508) in the code to check the fonts.

Would love for it to work for you but given I have no access to your OS, I can't debug for you. Would be great if you could help me with this.

On the other hand, to turn off this notification (it'll only pop once per session), you can set `Sys.unsetenv("LARES_FONT")`.

**Comment by louisjanin** [comment]
Indeed R.version$os is linux-gnu on my install
Sorry I couldnt properly test font_dirs, does this not get the right latest version ? 
```
remotes::install_github("laresbernardo/lares")
```
Here's what I get
```
> font_exists('Arial Narrow', font_dirs='/usr/share/fonts/truetype')
Error in font_exists("Arial Narrow", font_dirs = "/usr/share/fonts/truetype") : 
  unused argument (font_dirs = "/usr/share/fonts/truetype")
```

**Comment by laresbernardo** [comment]
Yes, that's right. But you must refresh your R session before you load the latest version and retry.

**Comment by louisjanin** [comment]
It works!
Now I just do this and it seems to work fine :1st_place_medal: 
```
library(Robyn)
lares::theme_lares(font_dirs="/usr/share/fonts/truetype")
```

**Comment by laresbernardo** [comment]
Amazing, thanks for confirming.
