### ISSUE TITLE
Working with factors

### ISSUE THREAD

**Issue by yousrihajri** [laresbernardo/lares#8]
Hi Bernardo
Thanks for the function plot_timeline which is very useful
My remark is that the function doesn't handle repeated Role or Place since the number of factors should be equal to the number of rows. I have just tried the same job name in 2 different companies and it throws an error.
Thanks

**Comment by laresbernardo** [comment]
You are absolutely right. Great point @yousrihajri 
Did you manage to fix that into the function or need some help with that?

**Comment by ShanSabri** [comment]
Another minor issues is that the factor levels for `type` is hardcoded. This causes problems in cases where we want to label "Work Experience" with "Professional Experience".

**Comment by laresbernardo** [comment]
> Another minor issues is that the factor levels for `type` is hardcoded. This causes problems in cases where we want to label "Work Experience" with "Professional Experience".

Great observation @ShanSabri fixed! 
Please run `devtools::install_github("laresbernardo/lares")`, close RStudio and then reopen it to try it.

**Comment by laresbernardo** [comment]
Fixed the order issue because of the factor's properties @yousrihajri 
Now the plot will order the events as they are posted into the function using another dummy variable.
Thanks for catching it!

**Comment by yousrihajri** [comment]
It works, thanks !
