### ISSUE TITLE
Error at h2o_automl?

### ISSUE THREAD

**Issue by wingraver** [laresbernardo/lares#9]
Hello Bernado, your package certainly has great potential use however I cannot it to work. With all attempts I get an error at "_results <- lares::h2o_automl(df = dfm, seed = seed, max_time = 60)_" or any such statement. The error message received = "**Error in h2o::h2o.automl(x = setdiff(names(df), "tag"), y = "tag", training_frame = as.h2o(train),  :   unused argument (exclude_algos = c("StackedEnsemble", "DeepLearning"))**". I have already successfully ran the update for the package so I'm wondering if the call to h2o is broken???

**Comment by laresbernardo** [comment]
Hello @wingraver Thanks for getting in contact!
I've just checked `h2o`'s documentation and there shouldn't be a problem with that parameter. The `exclude_algos` simply excludes some algorithms: http://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html
Please, try closing and opening RStudio again and retry. If you have just updated de library, you should restart your session (`lares` or `h2o`). 
Let me know if that helped!

**Comment by wingraver** [comment]
Hi @laresbernardo thanks for the quick response. I'm still getting the error even after closing/opening RStudio, restarting the session multiple times and running the update again. I am able to successfully execute h2o.automl from the h2o package (using a the diabetes dataset as a test) so I'm not sure what's happening between h2o_automl and get the h2o package?

Would my session info help? R 3.4.3 on Windows 7 x64

**Comment by laresbernardo** [comment]
Hey @wingraver 
Must be something in your configurations. I have just run this and everything ran as it should. Can you try it?
```
data(Diabetes, package="heplots")
df <- Diabetes %>% rename(tag = group)
results <- lares::h2o_automl(df, max_time = 30)
```

**Comment by wingraver** [comment]
Stranger and stranger... I reloaded my environment and tried installing the "heplots" package... I get an error message "unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:  Line starting '<html> ...' is malformed!"? Could it an issue with the version of RStudio (currently on 1.1.456)

**Comment by laresbernardo** [comment]
From here it seems that way @wingraver 
I currently have the `1.1.463` version and `R version 3.5.1`
Btw, I used that package/dataset because is the diabetes' dataset I found.. isn't it the one you are using?

**Comment by wingraver** [comment]
Okay so maybe it's got to do with the package versions... I'm using R version 3.4.3. The diabetes dataset was one you had mentioned in an article PimaIndianDiabetes (from the mlbench). Here's my session info...

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lares_4.3            dplyr_0.7.4          RevoUtilsMath_10.0.1 RevoUtils_10.0.7     RevoMods_11.0.0      MicrosoftML_9.3.0   
 [7] mrsdeploy_1.1.3      RevoScaleR_9.3.0     lattice_0.20-35      rpart_4.1-11

**Comment by wingraver** [comment]
It ran successfully (just now). I then restart RStudio but when I get to the lares::h2o_automl statement I still get the error.

**Comment by laresbernardo** [comment]
Try installing this as well:
devtools::install_github("r-lib/rlang", build_vignettes = TRUE)
 <https://github.com/r-lib/rlang#cheatsheet>

**Comment by wingraver** [comment]
Hi @laresbernardo thanks for all the additional feedback so far... still no improvement. Maybe I should have the IT team upgrade to R 3.5.1?

**Comment by laresbernardo** [comment]
Yes, I'd strongly recommend that. Let me know if that gets it fixed! I'll keep this ticket open util we finally understand what happened ;)
